config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :cars
  resources :packages, except: %i[index show]
  resources :requests, except: :index

  root 'welcome#index'
  get 'profile/', to: 'users#profile', as: 'profile'
  resource :profile, only: :show
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  enum size: [:small, :medium, :large, :extralarge]

 after_initialize do
    self.size ||= :medium if new_record?
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:edit, :update, :destroy]

  def new
    @car = current_user.cars.new
  end

  def edit; end

  def create
    @car = current_user.cars.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to profile_path, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_car
    @car = current_user.cars.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:size, :brand, :model, :color, :user_id)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="container" style="height:100vh">
      <div class="row">
        <div class="col-12 col-md-8 col-offset-md-2">
          <%= render 'shared/messages' %>
          <div class="card bg-light">
            <div class="card-body">
              <div class="card bg-light p-2">
              
                <div>
                  <%= form_with(model: @car, local: true) do |form| %>
                  <% if @car.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

                      <ul>
                      <% @car.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="form-group">
                    <%= form.select :size, Car.sizes.keys.map { |size| [size, size] } %>
                  </div>

                  <div class="form-group">
                    <%= form.label :brand %>
                    <%= form.text_field :brand, class:'form-control',:required => true%>
                  </div>

                  <div cclass="form-group">
                    <%= form.label :model %>
                    <%= form.text_field :model, class:'form-control', :required => true %>
                  </div>

                  <div class="form-group">
                    <%= form.label :color %>
                    <%= form.text_field :color , class:'form-control', :required => true %>
                  </div>

                  <div class="actions">
                    <%= form.submit %>
                  </div>
                  <% end %>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Size</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Color</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.size %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.user %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>Add a Car</h1>
<%= link_to 'Back','/', class: "btn btn-outline-primary my-2"  %>
<%= render 'form' %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Size:</strong>
  <%= @car.size %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>User:</strong>
  <%= @car.user %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>